#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX

# --------------------------------------------------------------
# Project name, used for binaries

NAME = TanDist

# --------------------------------------------------------------
# Files to build

FILES_DSP = TanDist.cpp

# --------------------------------------------------------------
# Do some magic

include ../../dpf/Makefile.plugins.mk


all: clap

# --------------------------------------------------------------